# render.yaml — Postiz on Render: Postgres + Key Value (Redis-compatible) + web
previews:
  generation: automatic

services:
  # Render Key Value (Redis-compatible) instance
  - type: keyvalue
    name: postiz-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow-all (change to a more restrictive CIDR for production)

  # Web service
  - type: web
    name: postiz-app
    plan: starter
    runtime: docker
    repo: https://github.com/postiz/postiz
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_URL
        value: "https://${RENDER_EXTERNAL_HOSTNAME}"
      - key: APP_KEY
        generateValue: true
      - key: TRUSTED_PROXIES
        value: "*"
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DATABASE_URL
        fromDatabase:
          name: postiz-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: postiz-redis
          property: connectionString

databases:
  - name: postiz-db
    plan: free
