services:
  # The Postiz Web Application
  - type: web
    name: postiz-app
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      # General App Settings
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: APP_KEY
        generateValue: true
      - key: TRUSTED_PROXIES
        value: "*"
      # Database Connection (linked to the database below)
      - key: DB_CONNECTION
        value: pgsql
      - from:
          type: postgresql
          name: postiz-db
          property: connectionString
      # Redis Connection (linked to the redis instance below)
      - from:
          type: redis
          name: postiz-redis
          property: connectionString

# Managed PostgreSQL Database for Postiz
databases:
  - name: postiz-db
    plan: free

# Managed Redis Instance for Caching & Queues
redis:
  - name: postiz-redis
    plan: free
